### PR TITLE
Add content:Introduction_to_Pandas_Library_and_DataFrames.md

### PR DESCRIPTION
**Pull request by kRiShNa-429407**
## PR Description

I created the content as per my approval. Please gone through it and let me know if there is any issue or not.
Thank you

## Related Issues

- Closes #

### Checklist

- [ ✅] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [ ✅] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [ ✅] I Agree

### CODE REVIEW

**Comment by kRiShNa-429407** [comment]
Please review it

**Comment by animator** [comment]
Remove the image
It is adding no value

**Comment by kRiShNa-429407** [comment]
Okk sir
Thank you

**Comment by kRiShNa-429407** [comment]
Done sir 
Please review

**Comment by kRiShNa-429407** [comment]
I made changes. Please review and merge it

**Comment by kRiShNa-429407** [comment]
I closed this request due to some technical reasons, but I open a new request by solving the issues

**Pull request closed without merging**
