### PR TITLE
Added OOPs

### LINKED ISSUE #240: Basics of Object Oriented Programming (OOP)
I would like to add about oop concepts . Please assign me this task under GSSOC'24

### PR DESCRIPTION
**Pull request by AmrutaJayanti**
## PR Description

Added Object Oriented Programming For Python

## Related Issues

- Closes #240 

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by AmrutaJayanti** [comment]
@animator Please approve my PR . I'm quite new to this GSSOC'2024 .
I ensured that this time I have done by the contribute guide and followed PR template

**Comment by animator** [comment]
Formatting is not correct.
Also it has codes with no explanation.

**Comment by AmrutaJayanti** [comment]
@animator I have formatted it and added explanation for codes . Please approve.

**Comment by AmrutaJayanti** [comment]
@animator This task is already merged, but you assigned me the same again. Please check.
I have made PR related to mini-project. Please approve

**Pull request merged**
