### PR TITLE
Added info about how to install NumPy in a system.

### PR DESCRIPTION
**Pull request by Yodha-Sudarsi**
## PR Description

Added installation process, about how to install NumPy library in python and updated the index.md accordingly.

## Related Issues
#78
- Closes [installing numpy #78](https://github.com/animator/learn-python/issues/78)

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by animator** [comment]
You have modified the PR template. You should mark the checkboxes properly:

`- [x]` instead of `- [Y]`

**Comment by Yodha-Sudarsi** [comment]
Good morning @animator , Updated the PR description as per the requirement. So can I move to next issue ?

**Comment by animator** [comment]
You have not followed the instructions properly.
Take a look at the file changes that were made in this merged PR https://github.com/animator/learn-python/pull/119 to understand how it is to be done.

**Comment by Yodha-Sudarsi** [comment]
Thank you @animator for clarifying. I've reviewed the file changes in PR #119 and understand how to proceed accordingly.

**Comment by Yodha-Sudarsi** [comment]
@animator you can check now, I updated the PR Description

**Comment by animator** [comment]
When did I mention that you need to update the description?
I clearly asked you to check file changes.
Closing this PR.

**Pull request closed without merging**
