### PR TITLE
Adding mini project word counter

### LINKED ISSUE #221: Added mini project word counter
This project counts the number of words entered in the input sentence and give the number (count) of words in output. Each element present in the text will be considered a letter, and a group of letters with a space will be considered a word. It takes string as input from user, and counts the total number of words in the string. This count is displayed as output.

### PR DESCRIPTION
**Pull request by Arpcoder**
## PR Description

Adding a mini project which counts the number of words entered in the input sentence and gives the number (count) of words in the output.

## Related Issues

- Closes #221 

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by animator** [comment]
The provided code has incorrect formatting.

**Comment by Arpcoder** [comment]
> The provided code has incorrect formatting.

I have updated the Indentation of the code.

**Comment by animator** [comment]
This project is not useful. 
We have already provided topic outlines in the Contributing Guide.
Kindly choose a useful section you will add and raise an issue.

**Comment by Arpcoder** [comment]
@animator I you were going to close this then why did you asked me to improve the indentation of the code?.. The project was explained in the issue, you would have closed it at that time only, instead of adding labels and assigning me..

**Pull request closed without merging**
