### PR TITLE
Created Library Management System for issue #184

### LINKED ISSUE #184: Create a Library Management System using Python
This project will be coded in Anaconda, Jupyter Notebook, Python pandas with the help of CSV. This code will mainly focus on the basic operations in a library like adding new books in library, issuing and submission of books, and searching books on the basis of their author and book name. Furthermore, the books that are not required will be deleted too.

This program will have six main functions:-

Adding new book
Issuing a book
Submitting issued book
Deleting a record
Searching a specific record
Displaying the records

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
## PR Description

_Add your description_
 This project is coded in Anaconda, Jupyter Notebook, Python pandas with the help of CSV. This software mainly focuses on the basic operations in a library like adding new books in library, issuing and submission of books, and searching books on the basis of their author and book name. Furthermore, the books that are not required can be deleted too .This software is easily accessible for all type of users.

This software has six main functions:-
1. Adding new book
2. Issuing a book
3. Submitting issued book
4. Deleting a record
5. Searching a specific record
6. Displaying the records

## Related Issues

- Closes #184 

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by Aditi22Bansal** [comment]
@animator 
Kindly review the PR...

This time I have done as per the contributing guidelines.
Edited the index.md file and added the file with extension [.md] and wrote the content in the markdown format.

**Comment by Aditi22Bansal** [comment]
@animator
Kindly review the PR and approve...

Sorry for the inconvenience regarding the previous PR, since I am quite new to gssoc.
This time I have done as per the contributing guidelines.
Edited the index.md file and added the file with extension [.md] and wrote the content in the markdown format.

**Comment by Aditi22Bansal** [comment]
@animator
Kindly review the PR and approve...

Sorry for the inconvenience regarding the previous PR, since I am quite new to gssoc.
This time I have done as per the contributing guidelines.
Edited the index.md file and added the file with extension [.md] and wrote the content in the markdown format.

**Comment by animator** [comment]
The content quality is not upto the mark:
- Hard coded paths
- Irrelevant image
- Using CSV as a database

I recommend you to pick some other simpler topic first.

**Pull request closed without merging**
