### PR TITLE
Add Content: Introduction to pandas and DataFrames in pandas.

### PR DESCRIPTION
**Pull request by kRiShNa-429407**
## PR Description

Added the Introduction of Pandas and DataFrames.

## Related Issues

- Closes #

### Checklist

- [✅ ] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [ ✅] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [✅ ] I Agree

### CODE REVIEW

**Comment by kRiShNa-429407** [comment]
Please review again and approve .

**Comment by animator** [comment]
You have not mentioned the issue this PR is closing

**Comment by kRiShNa-429407** [comment]
not the serious issue , by mistake i merged another branch in my main branch so i delete the content od that branch , so it raises the issue

**Comment by kRiShNa-429407** [comment]
i reforked and raise a new PR after deleting that content which by mistake added in my branch

**Comment by kRiShNa-429407** [comment]
there is no issue now you can review it.

**Comment by animator** [comment]
I am asking you to mention the github issue number this PR is resolving.

**Comment by kRiShNa-429407** [comment]
i solved the merge conflict issue

**Comment by kRiShNa-429407** [comment]
ok wait sir

**Comment by kRiShNa-429407** [comment]
#333

**Comment by kRiShNa-429407** [comment]
#194

**Comment by kRiShNa-429407** [comment]
basically i added the another member numpy content in my branch , it raises merge conflict issue , so when i delete it , it changes the existing content repo

**Comment by animator** [comment]
I don't know why you are having a difficulty in understanding a simple instruction.
You are giving me PR numbers when I am asking for the issue number which was assigned to you.
Closing this PR.
Raise a new one following the process properly.

**Pull request closed without merging**
