### PR TITLE
[Added Content] Tree traversal

### LINKED ISSUE #1214: [Add Content] : Tree Traversal
Hey @animator, I am a GSSoC'24 Contributor.

I'd like to contribute to your project by adding a section on tree traversal in Python. This will covers the 3 main types of the traversals.
->  Inorder traversal
-> Preorder traversal
-> Postorder traversal

Kindly assign this issue to me.

### PR DESCRIPTION
**Pull request by Ramya-korupolu**
## PR Description

I have added a section on tree traversal in the ds-algorithms section. This includes the 3 main types of the traversals.
-> Inorder traversal
-> Preorder traversal
-> Postorder traversal

Added images for better understanding along with code.

## Related Issues

- Closes #1214 

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [ ] I Agree

### CODE REVIEW

**Comment by Ramya-korupolu** [comment]
@animator Please review my Pull request

**Comment by ashitaprasad** [comment]
What is the source of images?

**Comment by Ramya-korupolu** [comment]
> What is the source of images?

Javatpoint - Tree Traversal

**Comment by ashitaprasad** [comment]
Copyright images are not accepted.

**Comment by Ramya-korupolu** [comment]
I could replace the images with the images that I will create.

**Comment by ashitaprasad** [comment]
Sure you can do that and raise a new PR

**Pull request closed without merging**
