### PR TITLE
Add Content : Introduction_to_Pandas _and Dataframes

### PR DESCRIPTION
**Pull request by kRiShNa-429407**
## PR Description

Add Content : Introduction to pandas and dataframes

## Related Issues

- Closes #

### Checklist

- [ ✅] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [✅ ] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [✅ ] I Agree

### CODE REVIEW

**Comment by kRiShNa-429407** [comment]
Please review and approve

**Comment by animator** [comment]
Closing this PR. It is invalid as you are modifying of existing repo contents.

**Comment by kRiShNa-429407** [comment]
sorry sir i am  not modifying it but facing some technical issues so i PR again.

**Comment by kRiShNa-429407** [comment]
please sir approve this

**Comment by kRiShNa-429407** [comment]
By mistake I merged the existing content into my branch so I just deleted it from my branch

**Pull request closed without merging**
