### PR TITLE
machine learning evaluation metrics and performance metrics

### LINKED ISSUE #802: Add content about machine learning evaluation metrics and performance metrics
I would like to add a section of " .machine learning evaluation metrics and performance metrics"
 Please assign me this task under GSSOC'2024 with appropriate level (1/2/3)

### PR DESCRIPTION
**Pull request by Pranshu-jais**
## PR Description
added content about  machine learning evaluation metrics and performance metrics in file Evaluation Metrics and Performance Metrics.md  under machine-learning folder 

_Add your description_
added contents on commonly and  mostly used  evaluation metrics and performance metrics in machine learning along with their formula 
## Related Issues

- Closes #802

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by Pranshu-jais** [comment]
sir  i tried to fork the repository  but  it was showing me that this repository is already forked and   when  i went to  correct topic folder for contribution index.md file  was not their . Sir please don't  close this issue and  guide me for the corrections i will have to do if thier is any in this issue

**Comment by ashitaprasad** [comment]
Some issue with your fork as index.md file is there .. edit and commit it.

**Comment by Pranshu-jais** [comment]
i have followed  contribution guide and made changes as you asked . kindly tell me what file changes are not correct

**Comment by Pranshu-jais** [comment]
earlier  i told you my problem  : 

> sir i tried to fork the repository but it was showing me that this repository is already forked and when i went to correct topic folder for contribution index.md file was not their . Sir please don't close this issue and guide me for the corrections i will have to do if thier is any in this issue

**Pull request closed without merging**
