### PR TITLE
Add Content: Pandas Introduction and DataFrames

### LINKED ISSUE #96: Add Content: Introduction and DataFrames in Pandas

### PR DESCRIPTION
**Pull request by kRiShNa-429407**
## PR Description

Added the content of "Pandas introduction and DataFrames"

## Related Issues

- Closes #96

### Checklist

- [✅ ] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [ ✅] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [ ✅] I Agree

### CODE REVIEW

**Comment by kRiShNa-429407** [comment]
Please review and approve.

**Comment by animator** [comment]
Stop being in a hurry to submit a PR.
You have still not addressed the following issue:
- Do not use HTML inside markdown.

**Comment by kRiShNa-429407** [comment]
Where?

**Comment by kRiShNa-429407** [comment]
please little address me where i used html?

**Comment by animator** [comment]
If you do not know where you have used HTML elements in the file, then I highly doubt you have even written this content. When you are contributing to a book it is expected the content is original and everything is cross-checked multiple times. Marking it as an ethical violation. Do not submit future PRs.

**Comment by kRiShNa-429407** [comment]
sir this is original , i first write it in my own jupyter notebook and export the same notebook as markdown

**Comment by kRiShNa-429407** [comment]
This is my first open source contribution , so please .
I sure next time there will be no mistake

**Comment by animator** [comment]
Okay... Now that you have spoken the truth.. Your ethics violation will be removed.
I am re-opening the issue.
Learn markdown, write the entire content in markdown and send a new PR.

**Comment by kRiShNa-429407** [comment]
Thank you so much  sir

**Comment by kRiShNa-429407** [comment]
should i re open the issue?

**Comment by animator** [comment]
Already reopened #96

**Comment by kRiShNa-429407** [comment]
please also reopen #211 and #414

**Comment by animator** [comment]
Later .. once you get your PR accepted.

**Comment by kRiShNa-429407** [comment]
okk i opend the pr

**Pull request closed without merging**
