### PR TITLE
Created Matplotlib beginner tutorial, Advanced Quiz game and updated index.md

### LINKED ISSUE #110: Basic Quiz game
I want to develop a basic  mcq quiz game where user can select from a particular genre and user gets the points scored in the end

### PR DESCRIPTION
**Pull request by ishaanv1206**
## PR Description

This is a simple Python script for a basic quiz game. It allows users to choose from different genres of quizzes including Sports, Entertainment, Physics, Chemistry, and Biology. The user selects a genre, and then answers multiple-choice questions related to that genre. After answering all the questions, the user's score is displayed. I created efficient code and also used built in datatypes. This updated version. I have explained in the markdown file for better understanding.

I created the Matplotlib tutorial and updated index.md

## Related Issues

- Closes #110 #158 

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by ishaanv1206** [comment]
Hi @animator 
I created a advanced version, previously i thought i have to create a basic version. I used several datatypes and wrote efficient, reusable code

**Comment by ishaanv1206** [comment]
@animator please see to it

**Comment by ishaanv1206** [comment]
@animator Please check my quiz commit and also matplotlib tutorial commit

**Comment by animator** [comment]
The file names should be in lowercase and separated by `-` instead fo `_`

**Comment by animator** [comment]
Also, both should be in two separate PRs.
Closing this PR. Raise 2 new PRs

**Pull request closed without merging**
