### PR TITLE
Add Content: "Introduction to Scikit learn and Getting Data ready for modelling"

### LINKED ISSUE #620: Add Content: Introduction to scikit-learn and get the data ready for modelling.
Please assign it to me.

### PR DESCRIPTION
**Pull request by kRiShNa-429407**
## PR Description

Content added on "Introduction to Scikit learn and Getting Data ready for modelling"

## Related Issues

- Closes #620

### Checklist

- [ ✅] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [✅ ] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [✅ ] I Agree

### CODE REVIEW

**Comment by animator** [comment]
It should be more about the capabilities of the library without any code.

**Comment by kRiShNa-429407** [comment]
Will add more 
It's just an introductory part

**Comment by kRiShNa-429407** [comment]
The more code will start from the next part.

As mentioned it's an introduction

**Comment by kRiShNa-429407** [comment]
Please look into 

I have deleted it

But you will tell 

Then  i re add it and raise a new PR

**Pull request closed without merging**
