### PR TITLE
Closes #294 - Mini Project : Password Strength Checker

### LINKED ISSUE #294: Mini Project : Password Strength Checker
A password strength  checker  checks  password  strength typically based on complexity, length, and character variety , and provides feedback for improvement, enhancing online security.

I agree to follow this project's Code of Conduct
 I'm a GSSoC'24 contributor
 I want to work on this issue

### PR DESCRIPTION
**Pull request by Anshika14528**
## PR Description
Created a simple password strength checker which:

##related issue
closes: #294 

- evaluates the strength of a user's password based on the presence of 
uppercase letters, lowercase letters, digits, spaces, and special characters.

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by Anshika14528** [comment]
@animator sir, can you please review it?

**Comment by animator** [comment]
You have not mentioned the issue this PR is closing

**Comment by Anshika14528** [comment]
Sorry @animator sir, I have updated the Pull request description 
Please review it again when you get time

**Comment by animator** [comment]
The folder structure is not correct. Go through some merged PRs to know how you should place it.

**Pull request closed without merging**
