### PR TITLE
Violin plots using matplotlib 

### LINKED ISSUE #1223: violin plots using matplotlib in plotting-visualization section
hello, i am a GSSoc'24 contributor and want to work on the issue of adding plotting violin plots using matplotlib tutorial under plotting visualization section. This section contains many plots like line plots, bar plots, pie charts using matplotlib, but not the violin plots which are used in determining and analyzing the distribution of data.

### PR DESCRIPTION
**Pull request by RajKhanke**
## PR Description

This PR contains entire document description and tutorial of plotting violin plots using matplotlib library in python along with the code snippets and visualization images.

## Related Issues

- Closes #1223 

### Checklist

- [X] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [X] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [X] I Agree

### CODE REVIEW

**Comment by RajKhanke** [comment]
@ashitaprasad please merge this along with Gssoc'24 label and level

**Comment by RajKhanke** [comment]
@ashitaprasad  please look at the review and merging this PR

**Comment by RajKhanke** [comment]
@ashitaprasad ?

**Comment by ashitaprasad** [comment]
You need to follow the contributing guide .. and update index.md file

**Comment by RajKhanke** [comment]
@ashitaprasad , now i have updated index.md , please look into my PR and merge it along with GSSoc'24 label and level (level 2 as assigned)

**Pull request merged**
