### PR TITLE
Added Threading Module In Advance Python

### LINKED ISSUE #810: Add Threading in Advance Python Module
I want to write about threading what and how it is performed in python,

### PR DESCRIPTION
**Pull request by Shraman-jain**
## PR Description

I have added a threading module in advance python section 

## Related Issues

- Closes #810 

### Checklist

- [X] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [X] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [X] I Agree

### CODE REVIEW

**Comment by Shraman-jain** [comment]
Please review this PR
Thank you:)

**Comment by Shraman-jain** [comment]
Please review this PR @animator @ashitaprasad 
Thank you:)

**Comment by ashitaprasad** [comment]
You have not provided any outputs for the cases.

**Comment by Shraman-jain** [comment]
Okay @ashitaprasad I will add the output and then re raise PR

**Comment by ashitaprasad** [comment]
Okay

**Comment by Shraman-jain** [comment]
Rasised the new PR. Please Check Thanks

**Pull request closed without merging**
