### PR TITLE
added API methods to the documentation

### LINKED ISSUE #74: Adding Explaination to API methods under API Development section
hey, @animator can i work on this

### PR DESCRIPTION
**Pull request by sujanMidatani7**
## PR Description

I have added the API Methods Introduction file to the API Development Folder

## Related Issues

- Closes #74 

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by animator** [comment]
Does not cover all the methods.

**Comment by sujanMidatani7** [comment]
> Does not cover all the methods.

ok then i will add all those

**Comment by sujanMidatani7** [comment]
> Does not cover all the methods.

@animator I have updated my request and added all the 9 http request methods to the documentation

**Comment by animator** [comment]
There is a lot of repetition.
You can describe the key feature for each method in one line and create a table to show the difference in other features (idempotence, has body, etc) with feature explanation.

**Comment by sujanMidatani7** [comment]
@animator check this out I have added tabular representation and modified the description of methods

**Comment by animator** [comment]
What about Response Body?
Explain CRUD, Accepts Request Body, Idempotent, Safe.

**Comment by sujanMidatani7** [comment]
@animator check this out i have added those and also  added definitions of crud, request body, idempotent, safe attributes of api 
methods

**Comment by animator** [comment]
You have modified the PR template. You should mark the checkboxes properly:

`- [x]` instead of `- [✅]`

**Comment by sujanMidatani7** [comment]
> You have modified the PR template. You should mark the checkboxes properly:
> 
> `- [x]` instead of `- [✅]`

@animator i have modified pr template please check that out

**Pull request merged**
