### PR TITLE
[Add content] advance python: JSON module

### LINKED ISSUE #365: [Add content] Advance Python : JSON Module
#197
Adding all content to one file and will reference in index. 

''
All added content should be in a well explained single markdown file.
Also, this suits Advanced Python instead of mini project. Add there. Closing this PR. Please raise a new PR.
''

_Originally posted by @animator in https://github.com/animator/learn-python/issues/197#issuecomment-2116376914_

### PR DESCRIPTION
**Pull request by Yatharth31**
## PR Description

This PR adds about JSON Module in Advance python section.

## Related Issues

- Closes #365 
- Reference PR #197 
### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by animator** [comment]
The code is a very specific use case and it will fail for many cases of json.
I recommend you that modify the topic ... instead of json to csv. 
Why dont you edit this file & file name and write about the features of json module along with examples.

**Comment by Yatharth31** [comment]
Okay, sure. Will do the changes and update.

**Comment by Yatharth31** [comment]
Hey @animator, done with the changes. Suggest if anything more is required to be added.

**Comment by animator** [comment]
Follow markdown syntax. Do not write HTML inside markdown.
Also there is some formatting issue with the content in line 70 & 117 (wierd coloring). Fix it.

**Comment by Yatharth31** [comment]
Followed markdown syntax. Removed weird coloring. Please merge the PR @animator.

**Comment by Yatharth31** [comment]
Hey @animator, any updates?

**Pull request merged**
