### PR TITLE
 K-Means Clustering Algorithm

### LINKED ISSUE #632: Add K-Means Clustering Algorithm
I would like to contribute to the repository by adding a comprehensive section on the K-Means Clustering algorithm, a popular unsupervised learning technique used for partitioning datasets into distinct clusters.

I am Participating in GSSOC'24.

### PR DESCRIPTION
**Pull request by revanth1718**
## PR Description

Added a comprehensive section on the K-Means Clustering algorithm, a popular unsupervised learning technique used for partitioning datasets into distinct clusters.

## Related Issues

- Closes #632 

### Checklist

- [X] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [X] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [X] I Agree

### CODE REVIEW

**Comment by ashitaprasad** [comment]
What is the source of content and images?

**Comment by revanth1718** [comment]
2 images from a publication and 2 images are the output generated from my code.

**Comment by ashitaprasad** [comment]
Mention the publication name and URL.

**Comment by revanth1718** [comment]
https://www.researchgate.net/figure/Components-of-the-objective-function-of-KM-algorithm-In-cluster-based-outlier-detection_fig3_339267868,  https://www.researchgate.net/figure/Demostration-of-K-means-algorithms_fig5_333457161

**Comment by revanth1718** [comment]
I have finished the work but lately uploaded the file . Please reopen the pull requests #1047 #1048 #1049

**Comment by ashitaprasad** [comment]
You need to mention the publication and link to it in the content reference section in the end.

**Comment by revanth1718** [comment]
you mean in the written .md file or in this conversation?

**Comment by ashitaprasad** [comment]
.md file

**Comment by revanth1718** [comment]
I added the content reference section in the end. check my updated .md file.

**Comment by revanth1718** [comment]
sorry , i will do it now.

**Comment by revanth1718** [comment]
once check the updated file.

**Comment by revanth1718** [comment]
this pull request is over or not?

**Pull request merged**
