### PR TITLE
Create library_management_system.py and Hangman_game_movie.py solving issue #184 and #185

### LINKED ISSUE #184: Create a Library Management System using Python
This project will be coded in Anaconda, Jupyter Notebook, Python pandas with the help of CSV. This code will mainly focus on the basic operations in a library like adding new books in library, issuing and submission of books, and searching books on the basis of their author and book name. Furthermore, the books that are not required will be deleted too.

This program will have six main functions:-

Adding new book
Issuing a book
Submitting issued book
Deleting a record
Searching a specific record
Displaying the records

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
## PR Description

_Add your description_
Library Management System

This project is a library management system coded in Anaconda using Jupyter Notebook, Python pandas, and CSV. It focuses on basic library operations such as adding new books, issuing and submitting books, searching books by author or title, and deleting unnecessary records. 

Main Functions:

1) Adding New Book:
Functionality: Adds new books to the library.
Input: Book details including title, author, etc.
Output: Updates the library database with the new book information.

2)Issuing a Book:
Functionality: Allows users to borrow books.
Input: Book details and borrower information.
Output: Records the book loan in the system.

3)Submitting Issued Book:
Functionality: Facilitates the return process for borrowed books. Input: Returned book details.
Output: Updates the library database to reflect the returned book.

4)Deleting a Record:
Functionality: Removes unnecessary records from the system. Input: Book details to be deleted.
Output: Deletes the specified record from the library database.

5) Searching a Specific Record:
Functionality: Enables users to search for books by author or title. Input: Search query (author name, book title, etc.). Output: Displays matching records found in the library database.

6)Displaying the Records:
Functionality: Shows all records currently stored in the library database. Output: Displays a comprehensive list of all books available in the library.

This project provides essential functionality for managing library operations efficiently.
Some screenshots are:
image
image
image
image
image
image

## Related Issues

- Closes #184 

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by Aditi22Bansal** [comment]
@animator 
Kindly review the PR

**Comment by Aditi22Bansal** [comment]
@animator
Kindly review the PR

**Comment by Aditi22Bansal** [comment]
@animator 
Kindly review the PR for issue #184 and #185

**Comment by animator** [comment]
You can't just add python codes.
You need to explain the project and code properly in a markdown file and follow the Contributing Guidelines.

**Pull request closed without merging**
