### PR TITLE
Added OOPs and SnakeGame

### PR DESCRIPTION
**Pull request by AmrutaJayanti**
#240 Added OOPs Concepts . Please approve

### CODE REVIEW

**Comment by AmrutaJayanti** [comment]
#241 Added SnakeGame to mini-projects. Please approve

**Comment by animator** [comment]
You have not mentioned the issue this PR is closing

**Comment by AmrutaJayanti** [comment]
Sir I have linked the issue 240 and 241

**Comment by animator** [comment]
Send 1 PR for 1 Issue.

**Pull request closed without merging**
