### PR TITLE
Add Content: Naïve Bayes Classifier in Python for Machine Learning

### PR DESCRIPTION
**Pull request by DivyanshiSingh00**
## PR Description

Added Content related to Naïve Bayes Classifier in Python for Machine Learning.

## Related Issues

- Closes https://github.com/animator/learn-python/issues/523

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by DivyanshiSingh00** [comment]
@animator please look into the pr and merge it if everything's okay or can give a feedback.

**Comment by ashitaprasad** [comment]
What is the source of content & image ?

**Comment by DivyanshiSingh00** [comment]
Image source is internet and the content reference includes the internet and a book that i have studied in my college duration (Bruce Ratner, Statistical and Machine-Learning Data Mining:Techniques for Better PredictiveModeling and Analysis)

**Comment by ashitaprasad** [comment]
Replace all images by those drawn yourself.
Also instead of image for equation, you can write equations in markdown. Read more on internet.

**Comment by DivyanshiSingh00** [comment]
Okay. Sure

**Comment by DivyanshiSingh00** [comment]
Okay. Sure

**Comment by ashitaprasad** [comment]
Raise a new PR when done.

**Pull request closed without merging**
