### PR TITLE
Exploratory Data Analysis using Python | Machine learning Application

### LINKED ISSUE #1204: Exploratory Data Analysis using Python | Machine learning Application
I would like to explain about EDA  using a Real time dataset.
Here is a short brief about EDA.

# Exploratory Data Analysis (EDA)

## Introduction

EDA is the process of examining datasets to summarize their main features using visual methods. It helps understand data, find patterns, spot anomalies, and form hypotheses.

## Key Objectives

- **Understand Data Structure**: Learn about variable types and distributions.
- **Detect Outliers**: Identify unusual data points.
- **Identify Patterns**: Discover relationships and trends.
- **Generate Hypotheses**: Form ideas for further testing.

## Tools

- **Python**: Pandas, Matplotlib, Seaborn.

### PR DESCRIPTION
**Pull request by Ganesh-Nagarampalli**
## PR Description

This pull request adds an exploratory data analysis (EDA) report on the Iris dataset. The report includes uni-variate, bi-variate, and multi-variate analyses, as well as correlation analysis. Key insights and observations are provided, highlighting the characteristics and relationships among the features and species in the dataset. This EDA report serves as a foundation for further analysis and modeling tasks.

## Related Issues

- Closes #1204

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by ashitaprasad** [comment]
What is the source of these images?

**Comment by Ganesh-Nagarampalli** [comment]
> What is the source of these images?

i have done EDA on IRIS dataset using google colab these are the output images of the code

**Comment by ashitaprasad** [comment]
Check the contributing guide. You are missing something.

**Comment by Ganesh-Nagarampalli** [comment]
Thank you, I forgot to update index.md, Now the issue is resolved

**Comment by Ganesh-Nagarampalli** [comment]
Hey @ashitaprasad  could you please merge this and assign labels to it.

**Pull request closed without merging**
