### PR TITLE
Create Dijkstra's_algorithm.md

### LINKED ISSUE #789: Adding content on Dijkstra's Algorithm
I want to add about Dijkstra's Algorithm, with images for explanation, i also have the md file almost ready. Please assign me this issue and add appropriate labels.

### PR DESCRIPTION
**Pull request by yashasvi232**
## PR Description

I have added about Dijkstra's Algorithm with images for better understanding.

## Related Issues

- Closes #789

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by ashitaprasad** [comment]
source of images?

**Comment by yashasvi232** [comment]
The images have been drawn by me using figma

**Comment by ashitaprasad** [comment]
You have to add images folder and update the markdown image paths.

**Comment by yashasvi232** [comment]
I've added the images in images folder. 

I meant to do that earlier only, but it was showing- Uploads are disabled. Turns out I was trying to upload it on the main file, and I did not notice that so I added the images that way.

**Pull request merged**
