### PR TITLE
Added OOPs Concept.

### PR DESCRIPTION
**Pull request by lakshay-111**
I added basic oops concept in it. However if you want me to add more advanced concepts of OOPs just let me know.

## PR Description

_Add your description_

## Related Issues

- Closes #

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by animator** [comment]
You have not mentioned the issue this PR is closing

**Comment by lakshay-111** [comment]
solved issue #73 Adding OOPs concept under the topic Advanced python.

**Comment by lakshay-111** [comment]
Resolved issue #73 Adding OOPs concept under the topic advanced python.

**Comment by animator** [comment]
You have named the file incorrectly. It should be `oops.md` not `filename.md`

**Comment by lakshay-111** [comment]
Changed name to oops.md now.

**Comment by lakshay-111** [comment]
So you're gonna merge it or not?

**Comment by animator** [comment]
It has conflicts with the existing content of `oops.md` file in the repo.
You can improve it with your content and send across a new PR.

**Pull request closed without merging**
