### PR TITLE
Assigned Issue: Dots and Boxes game using python

### PR DESCRIPTION
**Pull request by Kavin56**
## PR Description

I've just opened up an issue in the repository and it got assigned to me , regarding adding some new features and polishing up the UI of the game. Specifically, I'm looking to implement Single Player and Multiplayer modes, a customizable grid option, and score tracking. I'm really excited about this and I think I can do a great job with it.

## Related Issues

#272 Create Dot and boxes game using pygame library
issue no . Create Dot and boxes game using pygame library gssoc level2

image

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by animator** [comment]
Wonderful job. But, sadly this is not a mini project but a major project that you should upload on your GitHub profile.
Closing the PR.

**Comment by Kavin56** [comment]
ok Thank you!!!

**Comment by animator** [comment]
Do you even have an iota of shame. Copying [someone else](https://github.com/shrawani21)'s work and claiming it as your own. You are barred from contributing to this project.

**Comment by Kavin56** [comment]
I have contributed to that project and please don't disrespect without knowing the truth

this is the pull request to that project which is done by me: 

https://github.com/shrawani21/gamer_21/pull/43

image

please dont disrespect others without knowing the truth , and it really hurts

please remove the label ethics-violation

**Pull request closed without merging**
