### PR TITLE
Added Regression in Machine Learning

### PR DESCRIPTION
**Pull request by Yogeshkarma**
## PR Description

Added  Brief analysis of Regression followed by its types, Linear regression detailed analysis with code, assumption of linear regression and Metrics of Regression

## Related Issues
following are the related issues addressed in this PR

1. [Intro to Regression Models Under SkLearn #328](https://github.com/animator/learn-python/issues/328)
2. [Implementing Linear Regression Algorithm with Python #320](https://github.com/animator/learn-python/issues/320)

- Closes #
- [Addition of Regression #300](https://github.com/animator/learn-python/issues/300)

### Checklist

-  [ &#9745; ] I have gone through the [contributing guide](https://github.com/animator/learn-python/blob/main/CONTRIBUTING.md)
-  [ &#9745; ] I have updated my branch and synced it with project `main` branch before making this PR

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
4. No portion of the work has been copied from any other source without proper attribution.  
5. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [ &#9745; ] I Agree

### CODE REVIEW

**Comment by animator** [comment]
You have not mentioned the issue this PR is closing

**Comment by Yogeshkarma** [comment]
@animator I have mentioned in the Closes - sub section that it closes the issue that you assigned to me

**Comment by Yogeshkarma** [comment]
@animator I am currently a rookie to this, so I assumed that closes section correctly

**Comment by animator** [comment]
Don't worry. will review.

**Pull request merged**
